### ISSUE TITLE
开放一个OCR API

### ISSUE THREAD

**Issue by ch3n4y** [situ2001/gzhu_no_clock_in#1]
详细看 Chaney1024/YQTB  
目前成功率在90以上。

**Comment by situ2001** [comment]
谢谢推荐，但是我现在使用的OCR，经过简单调参和测试，可以达到接近100%的准确率。也许，在未来，我会考虑切换。

Thanks for your recommendation. But now, the accuracy of parsing the captcha using the existing OCR recognition can reaches nearly 100%. Maybe I will adopt the API you adviced in the future, but not now.
