### ISSUE TITLE
一个小bug

### ISSUE THREAD

**Issue by w0ngzz** [situ2001/gzhu_no_clock_in#13]
自动打卡的话，本人身体状况那一栏是没有选'正常'或者'不适'，希望可以修复。
![Screenshot_2022-04-02-08-52-16-036_com tencent wework](https://user-images.githubusercontent.com/34603964/161357679-c803b8bb-f880-4448-abba-3d953f5a7acd.jpg)

**Comment by CHuaLi** [comment]
在clock_in.py
 # add some entries to form中
 加上form_data['fieldSTQKbrstzk1'] = '1'
就可以了

**Comment by CHuaLi** [comment]
在clock_in.py
的#add some entries to form注释下面的语句里
加上form_data['fieldSTQKbrstzk1'] = '1'
就可以了

**Comment by situ2001** [comment]
fixed a389cb5a5e32f08b2c71eb8d10e081d4c67ad5e1
