### ISSUE TITLE
It's cool.

### ISSUE THREAD

**Issue by ghost** [situ2001/gzhu_no_clock_in#14]
Mabe one day we could have an auto programme for gzhu student，including auto-clock-in，auto-running,auto-5y,auto-zhihuishu,auto-baishusongdu,auto-xuexiqiangguo and so on.

**Comment by situ2001** [comment]
You may be interested in [auto-baishusongdu](https://github.com/situ2001/gzhu-jdsd-helper) :)

**Comment by CHuaLi** [comment]
经典诵读已经有人弄过了，https://github.com/Steve0x2a/GZHU_JDSD/tree/test，下载fuck_jdsd.py，fiddler抓取微信小程序经典诵读的包，取key的值，编辑fuck_jdsd.py第九行填入key，之后python fuck_jdsd.py即可

**Comment by CHuaLi** [comment]
经典诵读python版
https://github.com/Steve0x2a/GZHU_JDSD/tree/test
下载fuck_jdsd.py，
fiddler抓取微信小程序经典诵读的包，取key的值，
编辑fuck_jdsd.py第九行填入key，
之后python fuck_jdsd.py即可
