### ISSUE TITLE
请问怎么使用pushplus推送

### ISSUE THREAD

**Issue by CHuaLi** [situ2001/gzhu_no_clock_in#15]
（windows）环境变量设置了PPTKEY后在python里os.getenv('PPTKEY')能得到pushplus的token，但是每次运行后在pushplus并没有推送结果

**Comment by situ2001** [comment]
这就得问一下实现 pushplus 推送的contributor @when-hao 了

BTW, 手动发推送是否成功？

**Comment by when-hao** [comment]
是我的锅，等我修复一下，再提一个pr

**Comment by CHuaLi** [comment]
> 这就得问一下实现 pushplus 推送的contributor @when-hao 了
> 
> BTW, 手动发推送是否成功？

http://www.pushplus.plus/send?token=XXX&title=XXX&content=XXX&template=html
测试了推送是可以的
