### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by CHuaLi** [situ2001/gzhu_no_clock_in#17]
![image](https://user-images.githubusercontent.com/98687198/181246773-80035cbe-ea65-4393-a7bd-ef686df63567.png)
应把clock_in.py中    form_data['fieldSTQKbrstzk1'] = '1'
改为    form_data['fieldJBXXdrsfwc'] = '2'

**Comment by situ2001** [comment]
修改后的行为是？

**Comment by CHuaLi** [comment]
> 修改后的行为是？

就是,fieldSTQKbrstzk1已经失效了,换成了fieldJBXXdrsfwc而且value为2的时候那个当日是否外出才会勾选"否"

**Comment by situ2001** [comment]
done.
