### ISSUE TITLE
一个神奇的bug

### ISSUE THREAD

**Issue by Tangent-90C** [situ2001/gzhu_no_clock_in#5]
![微信图片_20210920122831](https://user-images.githubusercontent.com/28804414/133957236-4416f737-73fc-43db-bf7b-0d7b8480adeb.jpg)
在后台可以看到这个程序已经为我打卡了，但是有2个必选项目却没点？而且还提交成功了？？？

**Comment by situ2001** [comment]
预期行为
侧面说明我厂打卡辣鸡（
Btw,你可以提PR,F12一下就行
有空就会处理

**Comment by situ2001** [comment]
Fixed #7
